main:
  - name: Back to Home
    url: 'https://gaoxiaohan.com/'
    icon: '<i class="fas fa-home"></i>'
  - name: Blog
    identifier: blog
    params:
      icon: '<i class="fas fa-fw fa-blog text-warning"></i>'
      description: 'Taxonomy'
